### ISSUE TITLE
Ellipsis disappears from posts after loading MD plugin

### ISSUE THREAD

**Issue by cbebek** [terrylinooo/githuber-md#10] opened 2019-02-05 23:28 UTC
Hi Terry,

Not sure if this is a plugin issue but when I type an ellipsis, i.e. three dots ..., they appear in the middle of the line, not on the bottom. On posts that I wrote without your plugin enabled, they disappear entirely after loading your plugin.

**Comment by terrylinooo** [comment] 2019-02-06 15:34
@cbebek Hello.

It seems to be an issue that caused by the JavaScript part. I will look into it and fix it in next version.
Thanks for your feedback.
Have a good day!

**Comment by terrylinooo** [comment] 2019-03-23 17:45
@cbebek  I found the three dots `...` are transformed to `…` by Parsedown (which is Githuber MD's Markdown parser. I will create an option in setting page that allows users to replace `…` to `...`.

This setting option will be in 1.7.0, you can turn it on if you really want.

**Closed by terrylinooo** 2019-03-23 17:45 UTC
Labels: bug
